import './globals.css'
import { ReactNode } from 'react'
import { Roboto_Flex as Roboto } from 'next/font/google'
import Provider from '@/components/Provider'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.variable} overflow-x-hidden bg-[#202024] font-sans text-gray-100`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
